config/routes.rb
Rails.application.routes.draw do
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "signup", to: "users#index"
  post "signup", to: "users#create"
  get "login", to: "users#read"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "offers", to: "offers#index"
  get "newshops", to: "newshops#index"
  get "trending", to: "trendings#index"

  get "sellers/login", to: "sellers#read"
  get "sellers/signup", to: "sellers#index"
  post "sellers/signup", to: "sellers#create"
  post "sellers/login", to: "sessions#createseller"
  get "sellers/home", to: "homes#sellersindex"
  delete "sellers/logout", to: "sessions#sellerdestroy"

  post "additems", to: "homes#itemadd"
  get  "sellers/shop", to: "homes#addmyshop"
  post "addshop", to: "homes#shopadd"
  get '/shops/:shop_id/items', to: 'items#index', as: 'shop_items'
  post "cart", to: 'items#cart'
  get "carts", to: 'items#carts'
  post 'destroyitemcart', to: 'items#destroy_cart_item'
  get 'payment', to: 'items#payment'

  post 'orders', to:'items#placeorder'
  get 'searchshop', to: 'homes#search'
  post 'search', to:'homes#searchpost'
  post '/shops/:shop_id/search', to: 'homes#searchpost'
  get 'profile', to: 'users#profile'
  get 'updateprofile', to: 'users#update'
  put 'editprofile', to: 'users#editprofile'
  get 'sellersorder', to: 'sellers#myorder'
  get 'searchitems', to: 'homes#searchitems'
  root "homes#index"
  get 'root_path/:category2', to: 'homes#index', as: :root_with_params_category2
  get 'root_path/:category1', to: 'homes#index', as: :root_with_params_category1
  get 'root_path/:item_name', to: 'homes#index', as: :root_with_params_item_name
  get 'root_path/:shop_name', to: 'homes#index', as: :root_with_params_shop_name
  get 'root_path/:city/:area', to: 'homes#index', as: :root_with_params_city_and_area
  get 'locationform', to: 'homes#locationform'
  post 'currentlocation', to: 'homes#currentlocation'
  
end

app/models/seller.rb
class Seller < ApplicationRecord
    validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :password, presence: true, length: { minimum: 6 }
    validates :sellername, presence: true
    has_many :shops, dependent: :destroy
    has_many :items, dependent: :destroy
    has_many :orders, dependent: :destroy
    validates :confirm_password, presence: true
    
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController

  def index
    @user = Seller.new
  end

  def create
    @user = Seller.new(user_params)
    @user.password=encrypt(user_params[:password])
    @user.confirm_password=encrypt(user_params[:confirm_password])
    if @user.save
      session[:seller_id] = @user.id
      redirect_to sellers_home_path, notice: "Successfully created the account"
    else
      render :index, status: :unprocessable_entity
    end
  end

  def read
  end

  def update
  end

  def delete
  end

  def myorder
    if session[:seller_id]
      @orders=Order.where(seller_id: session[:seller_id])
    end
  end

  private

  def user_params

    params.require(:seller).permit(:email, :password, :address, :sellername,:confirm_password)
  end

  def encrypt(text)
    shift = 3  # You can adjust the shift value as needed
    encrypted_text = ""
    
    text.each_char do |char|
      if char.match(/[a-zA-Z]/)
        shift_amount = (char.downcase == char) ? 97 : 65
        encrypted_char = ((char.ord - shift_amount + shift) % 26 + shift_amount).chr
      else
        encrypted_char = char
      end
      encrypted_text += encrypted_char
    end
  
    return encrypted_text
  end




end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/sellers/create.html.erb
<h1>Sellers#create</h1>
<p>Find me in app/views/sellers/create.html.erb</p>

app/views/sellers/delete.html.erb
<h1>Sellers#delete</h1>
<p>Find me in app/views/sellers/delete.html.erb</p>

app/views/sellers/index.html.erb
<div class="flexing-create-user">
 <div class="para1-create-user">
    <h1 style="color: white;margin-left: 40px;">VIRTUAL MARKET HUB</h1>
    <h3 style="color: rgb(182, 62, 203);margin-left: 55px;"> Local Market Ka Virtual vocal</h3>
    <div class="inner">
      <img src="<%= asset_path("second-image.png") %>" alt="Description of the image" width="908px" height="500px" >
      
      
    </div>

 </div>
     
 <div class="para2-create-user">
    <div class=signup-user>
    <h1 style="color: rgb(182, 62, 203)"> Sign Up As Seller </h1>
    <%= form_with model: @user, url: sellers_signup_path do |form| %>
      <% if @user.errors.any? %>
          <div style="background-color: red">
            <% @user.errors.full_messages.each do |message| %>
            <div style="color: white;"><%= message %></div>
           <% end %>
          </div>
      <% end %>
      <div class="mb-3">
      <%= form.label :email, style: "color: white" %>
      <%= form.text_field :email, class: "form-control", placeholder: "xyz@gmail.com" %>
      </div>
      <div class="mb-3">
      <%= form.label :password, style: "color: white" %>
      <%= form.password_field :password, class: "form-control", placeholder: "password" %>
      </div>
      <div class="mb-3">
      <%= form.label :confirm_password, style: "color: white" %>
      <%= form.password_field :confirm_password, class: "form-control", placeholder: "confirm_password" %>
      </div>
      <div class="mb-3">
      <%= form.label :Username, style: "color: white" %>
      <%= form.text_field :sellername, class: "form-control", placeholder: "Username" %>
      </div>
      <div class="mb-3">
      <%= form.label :Address, style: "color: white" %>
      <%= form.text_field :address, class: "form-control", placeholder: "Address" %>
      </div>
      <div class="mb-3">
        <%= form.submit "Sign Up", class: "btn btn-primary" %>
        <%= link_to "Already a User! Click to login", sellers_login_path, style: "margin-left: 12px" %>
      </div>
    <% end %>
    </div>
 </div>
</div>

app/views/sellers/myorder.html.erb
<h1 style="margin-left:40%; margin-bottom:2%"> Order details☎️ </h1>

<table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">S.NO</th>
      <th scope="col">orrder_id</th>
      <th scope="col">Amount</th>
      <th scope="col">order_details</th>
    </tr>
  </thead>
  <tbody>
     <% if @orders %>
     <%cnt=0%>
      <% @orders.each do |order| %>
                  <tr>
                        <th scope="row"><%=cnt%></th>
                        <td><%=order.id%></td>
                        <td>₹<%=order.amount%></td>
                        <td><%=order.order_details%></td>
                  </tr>
                  <%cnt+=1%>
            <% end %>
      <%end%>
    
  </tbody>
</table>

app/views/sellers/read.html.erb
<div class="flexing-create-user">
 <div class="para1-create-user">
    <h1 style="color: white;margin-left: 40px;">VIRTUAL MARKET HUB</h1>
    <h3 style="color: rgb(182, 62, 203);margin-left: 55px;"> Local Market Ka Virtual vocal</h3>
    <div class="inner">
      <img src="<%= asset_path("second-image.png") %>" alt="Description of the image" width="908px" height="500px" >
      
      
    </div>

 </div>
     
 <div class="para2-create-user">
    <div class=signup-user>
    <h1 style="color: rgb(182, 62, 203)"> Login As a Seller </h1>
    <%if @check==false%>
      <div style="background-color: rgb(215, 62, 44);margin-bottom: 20px;border-radius: 5px;height: 80px;"><h4 style="color: white;margin-top: 13px;margin-left: 70px;padding-top: 22px;">Wrong credentials</h4></div>
    <%end%>
    <%= form_with  url: sellers_login_path do |form| %>
      <div class="mb-3">
      <%= form.label :email, style: "color: white" %>
      <%= form.text_field :email, class: "form-control", placeholder: "xyz@gmail.com" %>
      </div>
      <div class="mb-3">
      <%= form.label :password, style: "color: white" %>
      <%= form.password_field :password, class: "form-control", placeholder: "password" %>
      </div>
      <div class="mb-3">
        <%= form.submit "Log in", class: "btn btn-primary" %>
        <%= link_to "New User! Click to signup", sellers_signup_path, style: "margin-left: 12px" %>
      </div>
    <% end %>
    </div>
 </div>
</div>

app/views/sellers/update.html.erb
<h1>Sellers#update</h1>
<p>Find me in app/views/sellers/update.html.erb</p>