config/routes.rb
Rails.application.routes.draw do
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "signup", to: "users#index"
  post "signup", to: "users#create"
  get "login", to: "users#read"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "offers", to: "offers#index"
  get "newshops", to: "newshops#index"
  get "trending", to: "trendings#index"

  get "sellers/login", to: "sellers#read"
  get "sellers/signup", to: "sellers#index"
  post "sellers/signup", to: "sellers#create"
  post "sellers/login", to: "sessions#createseller"
  get "sellers/home", to: "homes#sellersindex"
  delete "sellers/logout", to: "sessions#sellerdestroy"

  post "additems", to: "homes#itemadd"
  get  "sellers/shop", to: "homes#addmyshop"
  post "addshop", to: "homes#shopadd"
  get '/shops/:shop_id/items', to: 'items#index', as: 'shop_items'
  post "cart", to: 'items#cart'
  get "carts", to: 'items#carts'
  post 'destroyitemcart', to: 'items#destroy_cart_item'
  get 'payment', to: 'items#payment'

  post 'orders', to:'items#placeorder'
  get 'searchshop', to: 'homes#search'
  post 'search', to:'homes#searchpost'
  post '/shops/:shop_id/search', to: 'homes#searchpost'
  get 'profile', to: 'users#profile'
  get 'updateprofile', to: 'users#update'
  put 'editprofile', to: 'users#editprofile'
  get 'sellersorder', to: 'sellers#myorder'
  get 'searchitems', to: 'homes#searchitems'
  root "homes#index"
  get 'root_path/:category2', to: 'homes#index', as: :root_with_params_category2
  get 'root_path/:category1', to: 'homes#index', as: :root_with_params_category1
  get 'root_path/:item_name', to: 'homes#index', as: :root_with_params_item_name
  get 'root_path/:shop_name', to: 'homes#index', as: :root_with_params_shop_name
  get 'root_path/:city/:area', to: 'homes#index', as: :root_with_params_city_and_area
  get 'locationform', to: 'homes#locationform'
  post 'currentlocation', to: 'homes#currentlocation'
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

    
    def index
        if params[:category2]
            @items=Item.where(category2: params[:category2])
            @rating_map=session[:rating_map]
        elsif params[:category1]
            @items=Item.where(category1: params[:category1])
            @rating_map=session[:rating_map]
        elsif params[:item_name]
            @rating_map=session[:rating_map]
            @items=Item.where(item_name: params[:item_name])
            @items1=Item.where(category1: @items.first.category1)
            @items2=Item.where(category2: @items.first.category2)
            
            

        elsif params[:shop_name]
            @shops=Shop.where(shop_name: params[:shop_name])
            @items=Item.where(shop_id: @shops.first.id)
            @rating_map=session[:rating_map]
            @shopRating_map=session[:shopRating_map]
        
        elsif params[:city] && params[:area]
            
            if session[:user_id]
                @user=User.find_by(id: session[:user_id])
            end
            @shops=Shop.where(city: params[:city], area: params[:area])
            @items=Item.joins(:shop).where(shops:{ city: params[:city], area: params[:area] })
            @rating_map=session[:rating_map]
            @shopRating_map=session[:shopRating_map]
            

        else
            if session[:user_id]
                @user=User.find_by(id: session[:user_id])
            end
            @shops=Shop.all
            @items=Item.all
            @rating_map={}
            @shopRating_map={}
            @items.each do |item|
                itemratings=Rating.where(item_id: item.id)
                sum=0
                count=0
                itemratings.each do |items|
                    sum=sum+items.rating
                    count+=1
                end
                @rating_map[item.id]=(sum.to_f/count).round(1)
            end
            session[:rating_map]=@rating_map
            @shops.each do |shop|
                allitems=Item.where(shop_id: shop.id)
                sum=0
                count=0
                allitems.each do |item|
                    sum+=@rating_map[item.id].to_i
                    count+=1
                end
                @shopRating_map[shop.id]=(sum.to_f/count).round(1)
            end
            
            puts @shopRating_map
            session[:shopRating_map]=@shopRating_map
            # puts @rating_map

            



        end
    end
    def sellersindex
        @checker3=false
        if session[:seller_id]
            @user=Seller.find_by(id: session[:seller_id])
        end   
    end
        
    
    def addmyshop
        if session[:seller_id]
            @user=Seller.find_by(id: session[:seller_id])
        end
    end
    
    def itemadd
        @checker=true
        @checkmate=false
        if session[:seller_id]
            seller_id = session[:seller_id]
            shop_id = Shop.find_by(seller_id: seller_id)&.id
             
            if shop_id
              # Create a new item and associate it with the seller and shop
              @item = Item.new(items_params)
              @item.seller_id = seller_id
              @item.shop_id = shop_id
              flash[:notice] = "Item added successfully."
              if @item.save
                @checker=true
                render :sellersindex, notice: "Successfully created the account"
              else
                @checker=false
                render :sellersindex, status: :unprocessable_entity
              end
            else
                @checker=false
                redirect_to sellers_shop_path
            end
        else
            @checker=false
            render :sellersindex, status: :unprocessable_entity
        end
    end

    
    def shopadd
        
        @checker=true
        if session[:seller_id]
            
            seller_id=session[:seller_id]
            @shop=Shop.new(shop_params)
            @shop.seller_id=seller_id
            if @shop.save
                redirect_to sellers_home_path
                @checker=true
            else
                @checker=false
                render :addmyshop, status: :unprocessable_entity
                
            end
        end
        
    end

    def search
        shop_id=params[:id]
        @shop=Shop.find(shop_id)
        item_name=params[:item_name]
        @itemsMatch=Item.where('lower(item_name) LIKE ?', "%#{item_name.downcase}%")
        @items=Item.where(shop_id: shop_id)
        
        

    end

    def searchitems
        item_name=params[:item_name]
        @items=Item.where('lower(item_name) LIKE ?', "%#{item_name.downcase}%")
        
        
        
    end

    def searchpost
        item_name=params[:shop_name]
        shop_name=params[:shop_name]
        @shops=Shop.where('lower(shop_name) LIKE ?', "%#{shop_name.downcase}%")
        @items=Item.where('lower(item_name) LIKE ?', "%#{item_name.downcase}%")
        @items_category1=Item.where('lower(category1) LIKE ?', "%#{item_name.downcase}%")
        category1=[]
        @items_category1.each do |item|
            category1.push(item.category1)
        end
        category1=category1.uniq
        @items_category2=Item.where('lower(category2) LIKE ?', "%#{item_name.downcase}%")
        category2=[]
        @items_category2.each do |item|
            category2.push(item.category2)
        end
        category2=category2.uniq
        respond_to do |format|
            
            format.turbo_stream do
                render turbo_stream: turbo_stream.update("search_results",partial: "homes/search_results", locals: {items: @items, item_name: item_name, items_category1: category1, items_category2: category2, shop_name: shop_name, shops: @shops})
                
            end
        end
        
        # item_name=params[:shop_name]
        # shop = Shop.find_by('lower(shop_name) LIKE ?', "%#{shop_name.downcase}%")
        # if shop
        #     redirect_to searchshop_path(id: shop.id, item_name: item_name)
        
        # else
        #     redirect_to searchitems_path(item_name: item_name)
        # end
        

    end

    def locationform
        
        
    end

    def currentlocation
        session[:city]=params[:city]
        session[:area]=params[:area]
        redirect_to root_path(city: params[:city], area: params[:area])
    end
    

    private
    def items_params
        params.permit(:item_name, :quantity, :summary, :price, :image)
    end

    def shop_params
        params.permit(:shop_name,:shop_summary,:shop_image)
    end
end

app/views/homes/_search_results.html.erb
<%if item_name !=""%>
    <% items.each do |item|%>
        <div style="margin-left:4px;margin-top:10px; font-size:21px"><%= link_to item.item_name, root_path(item_name: item.item_name), style: "margin-left:4px;margin-top:10px; font-size:21px;color: black; text-decoration: none;" %></div>
        <hr>
    <%end%>
    <% items_category1.each do |item|%>
        <div style="margin-left:4px;margin-top:10px; font-size:21px"><%= link_to item, root_path(category1: item), style: "margin-left:4px;margin-top:10px; font-size:21px;color: black; text-decoration: none;" %></div>
        <hr>
    <%end%>
    <% items_category2.each do |item|%>
        <div style="margin-left:4px;margin-top:10px; font-size:21px"><%= link_to item, root_path(category2: item), style: "margin-left:4px;margin-top:10px; font-size:21px;color: black; text-decoration: none;" %></div>
        <hr>
    <%end%>
<%end%>
    <%if shop_name !=""%>
        <% shops.each do |shop|%>
            <div style="margin-left:4px;margin-top:10px; font-size:21px"><%= link_to shop.shop_name, root_path(shop_name: shop.shop_name), style: "margin-left:4px;margin-top:10px; font-size:21px;color: black; text-decoration: none;" %></div>
            <hr>
        <%end%>
    <%end%>

app/views/homes/addmyshop.html.erb
<h1>You don't have a shop yet please add it then only you can add items </h1>
<% if @user %>
    Logged in as: <%= @user.email %>
    <%= button_to "Logout", sellers_logout_path, method: :delete, class: "btn btn-primary"%>
<%end%>
<div class="para2-create-user" style="background-color : white;">
    <div class=signup-user>
    <h1 style="color: rgb(182, 62, 203)"> ADD SHOP </h1>
    <%= form_with model: @shop, url: addshop_path do |form| %>
      <% if @checker==false %>
         <div style="background-color: red; height:50px;"><h5>error please check your fields</h5></div>
      <%end%>
      <div class="mb-3">
      <%= form.label :shop_name %>
      <%= form.text_field :shop_name, class: "form-control" %>
      </div>
      <div class="mb-3">
      <%= form.label :shop_summary %>
      <%= form.text_field :shop_summary, class: "form-control" %>
      </div>
      <div class="mb-3">
         <%=form.label :shop_image %>
         <%=form.file_field :shop_image %>
      </div>
      
    
      <div class="mb-3">
        <%= form.submit "ADD SHOP", class: "btn btn-primary" %>
        
      </div>
    <% end %>
    </div>
 </div>
 

app/views/homes/search.html.erb
<h1>Your searched shop</h1>
<% if @shop %>
    <div class="card" style="margin-right: 40px; margin-left: 75px; margin-bottom: 40px;">
        <% if @shop.shop_image.present? %>
            <%= link_to shop_items_path(@shop), style: "text-decoration: none; color: inherit;" do %>
            <%= image_tag(@shop.shop_image, style: "width: 300px; height: 250px") %>
            <% end %>
        <% end %>
        <h1><%= @shop.shop_name %></h1>
        <p class="price"><%= @shop.shop_summary %></p>
    </div>
<%end%>

<h1>Matched items results </h1>
<div class="flex-container" style="margin-top: 100px">
  <% @itemsMatch.each do |item| %>
    <div class="card" style="margin-right: 40px; margin-left: 75px; margin-bottom: 40px;border-radius: 10px;">
      <% if item.image.present? %>
          <%= image_tag(item.image, style: "width: 300px; height: 250px") %>
      <% end %>
      <h1><%= item.item_name %></h1>
      <% random_number = rand(10..50).to_f / 10 %>
      <p style="font-size: medium;"><%=random_number %>⭐</p>
      <p class="price"><%#= item.summary %></p>
      <p class="price">₹<%= item.price %></p>
      <p class="price">Remaining: <%= item.quantity %></p>
      <%= form_tag({ controller: "items", action: "cart", method: "post" }) do %>
        <%= hidden_field_tag :item_id, item.id %>
        <%= label_tag :quantity, "Quantity:" %>
        <%= number_field_tag :quantity, 1, min: 1, max: item.quantity, style: "border-radius: 10px; border: 2px solid lightgreen;" %>
        <%= submit_tag "Add to Cart", class: "add-to-cart-button btn btn-primary", style: "margin-bottom:12px" %>
      <% end %>
    </div>
  <% end %>
</div>



<h1>Recomended items </h1>
<div class="flex-container" style="margin-top: 100px">
  <% @items.each do |item| %>
    <div class="card" style="margin-right: 40px; margin-left: 75px; margin-bottom: 40px;border-radius: 10px;">
      <% if item.image.present? %>
          <%= image_tag(item.image, style: "width: 300px; height: 250px") %>
      <% end %>
      <h1><%= item.item_name %></h1>
      <% random_number = rand(10..50).to_f / 10 %>
      <p style="font-size: medium;"><%=random_number %>⭐</p>
      <p class="price"><%#= item.summary %></p>
      <p class="price">₹<%= item.price %></p>
      <p class="price">Remaining: <%= item.quantity %></p>
      <%= form_tag({ controller: "items", action: "cart", method: "post" }) do %>
        <%= hidden_field_tag :item_id, item.id %>
        <%= label_tag :quantity, "Quantity:" %>
        <%= number_field_tag :quantity, 1, min: 1, max: item.quantity, style: "border-radius: 10px; border: 2px solid lightgreen;" %>
        <%= submit_tag "Add to Cart", class: "add-to-cart-button btn btn-primary", style: "margin-bottom:12px" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/homes/searchitems.html.erb
<h1>it's searchitems page </h1>
<div class="flex-container" style="margin-top: 100px">
  <% @items.each do |item| %>
    <div class="card" style="margin-right: 40px; margin-left: 75px; margin-bottom: 40px;border-radius: 10px;">
      <% if item.image.present? %>
          <%= image_tag(item.image, style: "width: 300px; height: 250px") %>
      <% end %>
      <h1><%= item.item_name %></h1>
      <% random_number = rand(10..50).to_f / 10 %>
      <p style="font-size: medium;"><%=random_number %>⭐</p>
      <p class="price"><%#= item.summary %></p>
      <p class="price">₹<%= item.price %></p>
      <p class="price">Remaining: <%= item.quantity %></p>
      <%= form_tag({ controller: "items", action: "cart", method: "post" }) do %>
        <%= hidden_field_tag :item_id, item.id %>
        <%= label_tag :quantity, "Quantity:" %>
        <%= number_field_tag :quantity, 1, min: 1, max: item.quantity, style: "border-radius: 10px; border: 2px solid lightgreen;" %>
        <%= submit_tag "Add to Cart", class: "add-to-cart-button btn btn-primary", style: "margin-bottom:12px" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/homes/sellersindex.html.erb
<h1 style="margin-left:40%"> sellers Home page </h1>
<div style="display: flex;flex-direction: row;">
<div style="margin-right: 70%;"><%= link_to "My orders", sellersorder_path, class:"btn btn-primary" %></div>
<% if @user %>
    Logged in as: <%= @user.email %>
    <%= button_to "Logout", sellers_logout_path, method: :delete, class: "btn btn-primary"%>
<%end%>
</div>


<div class="para2-create-user" style="background-color : white;">
    <div class=signup-user>
    <h1 style="color: rgb(182, 62, 203)"> ADD items </h1>
    <%= form_with model: @item, url: additems_path do |form| %>
      <% if @checker==false %>
         <div style="background-color: red; height:50px;"><h5>error please check your fields</h5></div>
      <%end%>
      <% if @checkmate==true %>
         <div style="background-color: green; height:50px;"><h5>Items added successfully</h5></div>
      <%end%>
      <div class="mb-3">
      <%= form.label :item_name %>
      <%= form.text_field :item_name, class: "form-control" %>
      </div>
      <div class="mb-3">
      <%= form.label :summary %>
      <%= form.text_field :summary, class: "form-control" %>
      </div>
      <div class="mb-3">
         <%=form.label :image %>
         <%=form.file_field :image %>
      </div>
      <div class="mb-3">
      <%= form.label :quantity %>
      <%= form.text_field :quantity, class: "form-control" %>
      </div>
      <div class="mb-3">
      <%= form.label :price %>
      <%= form.text_field :price, class: "form-control" %>
      </div>
    
      <div class="mb-3">
        <%= form.submit "ADD ITEMS", class: "btn btn-primary" %>
        
      </div>
    <% end %>
    </div>
 </div>




 