config/routes.rb
Rails.application.routes.draw do
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "signup", to: "users#index"
  post "signup", to: "users#create"
  get "login", to: "users#read"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "offers", to: "offers#index"
  get "newshops", to: "newshops#index"
  get "trending", to: "trendings#index"

  get "sellers/login", to: "sellers#read"
  get "sellers/signup", to: "sellers#index"
  post "sellers/signup", to: "sellers#create"
  post "sellers/login", to: "sessions#createseller"
  get "sellers/home", to: "homes#sellersindex"
  delete "sellers/logout", to: "sessions#sellerdestroy"

  post "additems", to: "homes#itemadd"
  get  "sellers/shop", to: "homes#addmyshop"
  post "addshop", to: "homes#shopadd"
  get '/shops/:shop_id/items', to: 'items#index', as: 'shop_items'
  post "cart", to: 'items#cart'
  get "carts", to: 'items#carts'
  post 'destroyitemcart', to: 'items#destroy_cart_item'
  get 'payment', to: 'items#payment'

  post 'orders', to:'items#placeorder'
  get 'searchshop', to: 'homes#search'
  post 'search', to:'homes#searchpost'
  post '/shops/:shop_id/search', to: 'homes#searchpost'
  get 'profile', to: 'users#profile'
  get 'updateprofile', to: 'users#update'
  put 'editprofile', to: 'users#editprofile'
  get 'sellersorder', to: 'sellers#myorder'
  get 'searchitems', to: 'homes#searchitems'
  root "homes#index"
  get 'root_path/:category2', to: 'homes#index', as: :root_with_params_category2
  get 'root_path/:category1', to: 'homes#index', as: :root_with_params_category1
  get 'root_path/:item_name', to: 'homes#index', as: :root_with_params_item_name
  get 'root_path/:shop_name', to: 'homes#index', as: :root_with_params_shop_name
  get 'root_path/:city/:area', to: 'homes#index', as: :root_with_params_city_and_area
  get 'locationform', to: 'homes#locationform'
  post 'currentlocation', to: 'homes#currentlocation'
  
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
    def index
    end
end

app/views/offers/index.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <div class="navbar-brand"><%= link_to "HOME", root_path, style: "color: black; font-size: 20px; padding-left: 15px; text-decoration: none;" %></div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <div class="nav-link active" aria-current="page">
           <%= link_to "OFFERS", offers_path, style: "color: green; font-size: 20px; padding-left: 15px; text-decoration: underline;" %>
          </div>
        </li>
        <li class="nav-item">
          <div class="nav-link active" aria-current="page">
           <%= link_to "NEW", newshops_path, style: "color: black; font-size: 20px; padding-left: 15px; text-decoration: none;" %>
          </div>
        </li>
        <li class="nav-item">
          <div class="nav-link active" aria-current="page">
           <%= link_to "TRENDING", trending_path, style: "color: black; font-size: 20px; padding-left: 15px; text-decoration: none;" %>
          </div>
        </li>
        <li class="nav-item">
          <div class="nav-link active" aria-current="page">
           <%= link_to "CART🛒", carts_path, style: "color: black; font-size: 20px; padding-left: 15px; text-decoration: none;" %>
          </div>
        </li>
        <% if @user==nil %>
          <li class="nav-item">
            <div class="nav-link active" aria-current="page">
            <%= link_to "Login", login_path, class: "btn btn-primary" %>
            </div>
            </li>
        <% end %>
        <% if @user %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="font-size: 20px;color: black;margin-left:15px">
            EDIT PROFILE
          </a>
          
            <ul class="dropdown-menu">
            
              <li><a class="dropdown-item" href="#">
                <% if @user %>
                    Logged in as: <%= @user.email %>
                <% else %>
                    <%= link_to "Login", login_path, style: "color: black; font-size: 20px; padding-left: 15px; text-decoration: none;" %>
                    <hr>
                    <%= link_to "Signup", signup_path, style: "color: black; font-size: 20px; padding-left: 15px; text-decoration: none;" %>
                    <hr>
                <% end %> 
              </a></li>
              <% if @user %>
                <li class="dropdown-item">
                <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-primary" %>
                <hr>
                </li>
              <% end %>
              <li><%= link_to "VIEW PROFILE", profile_path, style: "color: black; font-size: 20px; padding-left: 15px; text-decoration: none;" %></li>
            </ul>
            
        </li>
        <% end %>
      </ul>
      <%# <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> %>
      <!-- app/views/shops/new.html.erb -->


      <%= form_tag('search', method: 'post') do %>
        <div class="d-flex flex-row justify-content-center align-items-center">
          <div class="mr-2">
            <%= text_field_tag 'shop_name', nil, class: 'form-control', placeholder: 'Search shop here' %>
          </div>
          <div>
            <%= submit_tag 'Search', class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>


    </div>
  </div>
</nav>