config/routes.rb
Rails.application.routes.draw do
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "signup", to: "users#index"
  post "signup", to: "users#create"
  get "login", to: "users#read"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "offers", to: "offers#index"
  get "newshops", to: "newshops#index"
  get "trending", to: "trendings#index"

  get "sellers/login", to: "sellers#read"
  get "sellers/signup", to: "sellers#index"
  post "sellers/signup", to: "sellers#create"
  post "sellers/login", to: "sessions#createseller"
  get "sellers/home", to: "homes#sellersindex"
  delete "sellers/logout", to: "sessions#sellerdestroy"

  post "additems", to: "homes#itemadd"
  get  "sellers/shop", to: "homes#addmyshop"
  post "addshop", to: "homes#shopadd"
  get '/shops/:shop_id/items', to: 'items#index', as: 'shop_items'
  post "cart", to: 'items#cart'
  get "carts", to: 'items#carts'
  post 'destroyitemcart', to: 'items#destroy_cart_item'
  get 'payment', to: 'items#payment'

  post 'orders', to:'items#placeorder'
  get 'searchshop', to: 'homes#search'
  post 'search', to:'homes#searchpost'
  post '/shops/:shop_id/search', to: 'homes#searchpost'
  get 'profile', to: 'users#profile'
  get 'updateprofile', to: 'users#update'
  put 'editprofile', to: 'users#editprofile'
  get 'sellersorder', to: 'sellers#myorder'
  get 'searchitems', to: 'homes#searchitems'
  root "homes#index"
  get 'root_path/:category2', to: 'homes#index', as: :root_with_params_category2
  get 'root_path/:category1', to: 'homes#index', as: :root_with_params_category1
  get 'root_path/:item_name', to: 'homes#index', as: :root_with_params_item_name
  get 'root_path/:shop_name', to: 'homes#index', as: :root_with_params_shop_name
  get 'root_path/:city/:area', to: 'homes#index', as: :root_with_params_city_and_area
  get 'locationform', to: 'homes#locationform'
  post 'currentlocation', to: 'homes#currentlocation'
  
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :seller
  belongs_to :shop
  validates :item_name, presence: true
  validates :quantity, numericality: { greater_than_or_equal_to: 0 }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  has_one_attached :image
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
   

    def index
        if session[:user_id]
            @user=User.find_by(id: session[:user_id])
        end
        @items=Item.where(shop_id: params[:shop_id])
        @rating_map = session[:rating_map]
        puts @rating_map
        session[:tempshop_id]=params[:shop_id]
    end

    def cart
        if session[:user_id]
            session[:cart_data] ||= {}
            item_id=params[:item_id]
            session[:cart_data][item_id]=params[:quantity]
            redirect_to carts_path
        end
        
        
        

    end

    def carts
        if session[:user_id]
            
            @user=User.find_by(id: session[:user_id])
            
            @data=session[:cart_data]
            item_ids=session[:cart_data].keys
            @items=Item.where(id: item_ids)
            @tempshop_id=session[:tempshop_id]
        end
    end

    def destroy_cart_item
        @data=session[:cart_data]
        @data.delete(params[:id])
        redirect_to carts_path
    end


    def payment
        if session[:user_id]
            @order=Order.new
            @data=params[:data]
            item_ids=@data.keys
            @items=Item.where(id: item_ids)
            @total_amount = params[:total_amount].to_i
            @user_id=session[:user_id]
            @user=User.find_by(id: @user_id)
            @shop_id=session[:tempshop_id]
            @seller_id = Shop.find_by(id: @shop_id)&.seller_id


        
        end
    end

    def placeorder
        @order=Order.new(order_params)
        @order.user_id=session[:user_id]
        


        if @order.save
            redirect_to root_path, notice: "order placed succesfully"
        
        else
            render json: { error: 'Your error message here' }, status: :unprocessable_entity
          
          
        end
    end
 

    private
    def order_params
        params.require(:order).permit(:seller_id, :shop_id, :order_details, :payment_check, :amount)
    end
    def to_bool(str)
        str.downcase == 'true'
    end



    
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/carts.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary" style="position:sticky;top:0px;z-index:5000;border-bottom: 5px solid green;">
    <div style="">
      <%= image_tag('logo-final.jpg', alt: 'Example Logo', style: 'height: 60px; width: 90px;') %>
    </div>

    <div class="container-fluid">
      <div class="navbar-brand" style="position:relative;bottom:1px"><%= link_to "HOME", root_path, style: "color: black;font-weight:700; font-size: 20px; padding-left: 15px;text-decoration: none;position:relative;top:4px" %></div>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <div class="nav-link active" aria-current="page" style="position:relative; top:3px">
            <%= link_to "OFFERS", offers_path, style: "color: black;font-weight:700; font-size: 20px; padding-left: 15px; text-decoration: none;" %>
            </div>
          </li>
      <li>
      <% if @user %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="font-size: 20px;color: black;margin-left:15px;position:relative;top:3px">
              <b>PROFILE</b>
            </a>
            
              <ul class="dropdown-menu">
              
                <li><a class="dropdown-item" href="#">
                  <% if @user %>
                      <div style="display:flex;flex-direction:row;">
                        <p class="logged-text" style="margin-right:5px;">Login as: </p> <p class="email-log"><%= @user.email %></p>
                      </div>
                  <% else %>
                      <%= link_to "Login", login_path, style: "color: black; font-size: 20px; padding-left: 15px; text-decoration: none;" %>
                      <hr>
                      <%= link_to "Signup", signup_path, style: "color: black; font-size: 20px; padding-left: 15px; text-decoration: none;" %>
                      <hr>
                  <% end %> 
                </a></li>
                <% if @user %>
                  <li class="dropdown-item">
                  <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-primary", style:"background-color:red;margin-bottom:10px;position:absolute;bottom:53px" %>
                  <hr>
                  </li>
                <% end %>
                <li><%= link_to "VIEW PROFILE", profile_path, style: "text-decoration:none;", class:"profile-v" %></li>
              </ul>
              
          </li>
          <% end %>
    </li>
          
          <li class="nav-item" style="position:relative">
            <div class="nav-link active" aria-current="page" style="position:relative;top:3px">
            <%= link_to "CART🛒", carts_path, style: "color: green;font-weight:700; font-size: 20px; padding-left: 15px; text-decoration: underline;" %>
            </div>
          </li>
          <% if @user==nil %>
            <li class="nav-item">
              <div class="nav-link active" aria-current="page">
              <%= link_to "Login", login_path, class: "btn btn-primary", style:"background-color:green;" %>
              </div>
              </li>
          <% end %>
          
        </ul>
        
        <div style="display:flex;flex-direction:column;position: absolute; top: 12px; left: 1035px; z-index: 1000;margin-top:10px">
          <%= form_tag('search', method: 'post') do %>
            <div class="d-flex flex-row justify-content-center align-items-center">
              <div class="mr-5" style="width:300px;margin-left:0px">
                <%= text_field_tag 'shop_name', nil, class: 'form-control', placeholder: '🔍 shop and items',oninput: "this.form.requestSubmit()", style:"border: 2px ridge green" %>
              </div>
              
            </div>
          <% end %>
          <div id="search_results" style="background-color:white"></div>
        </div>
        <div style="display:flex;flex-direction:row;position:absolute;left:550px;top:27px;">
          
          <%= link_to image_tag("location_logo.png", alt: "Image Description",style:"height: 30px;", id:"show-location-form")%>
          <%if session[:city] && session[:area]%>
            <div style="color: #3a3d3a; font-style: italic;font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;"><%= "#{session[:area]}, #{session[:city]}" %></div>
          <%end%>
          
        </div>


      </div>
    </div>
    
  </nav>




<div style="display: flex;flex-direction:column;align-items: center;background-color: rgb(197, 154, 236);"><h1>ADDED ITEMS IN THE CART🛒</h1></div>
<% if @tempshop_id %>
 <div style="position:absolute;bottom:475px;"><%= link_to "MENU🔙", shop_items_path(shop_id: @tempshop_id), class: "", class:"first-one-div", style:"text-decoration:none;color:green" %></div>
<%end%>
<%total_amount=0%>
<div class="flex-container" style="margin-top: 100px;">

    <%if @items %>
        <% @items.each do |item| %>
            <div class="card" style="margin-right: 40px; margin-left: 75px; margin-bottom: 40px;">
            <% if item.image.present? %>
                <%= image_tag(item.image, style: "width: 300px; height: 250px") %>
            <% end %>
            <h1><%= item.item_name %></h1>
            <p class="price"><%#= item.summary %></p>
            <p class="price">₹<%= item.price %></p>
            <p class="price">x <%= @data[item.id.to_s]%></p>
            <% total_amount += (item.price.to_i) * (@data[item.id.to_s].to_i) %>
            <%= form_with(url: { controller: 'items', action: 'destroy_cart_item', id: item.id }, method: :post) do |form| %>
                <%= form.submit 'Remove from Cart', class: 'btn btn-danger', style:"margin-bottom:20px"  %>
            <% end %>
            </div>
        <% end %>
    <% end %>

</div>
<div style="display:flex;flex-direction:row-reverse;">
<div style="position:fixed;top:500px;">
<div style="background-color:rgb(144, 228, 144);height:50px;display:flex;flex-direction:row-reverse;margin-right:40px;padding-right:100px;margin-bottom: 50px;">
 <h1 style="font-size: 18px; font-weight: bold; color: #333;padding-left:50px;margin-top:10px;margin-left:10px;width:fit-content;">Total Amount : ₹<%= total_amount %></h1>
 </div>
<div style="margin-right: 30px;margin-top: 5px;position:absolute;bottom:10px;right:20px;"><%= link_to "Go to Payment", payment_path(data: @data, total_amount: total_amount), class: "btn btn-primary", style:"background-color:green" %></div>

</div>
</div>

 <footer class="bg-dark text-light py-4">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <h4>About Us</h4>
          <p> we are virtu Market hub that allows you to shop from your favourite  shop in yur city</p>
        </div>
        <div class="col-md-4">
          <h4>Quick Links</h4>
          <ul class="list-unstyled">
            <li><a href="#">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Services</a></li>
            <li><a href="#">Contact</a></li>
          </ul>
        </div>
        <div class="col-md-4">
          <h4>Contact Us</h4>
          <address>
            
            <p>haridwar, uttarakhand, 249408</p>
            <p>Email: info@example.com</p>
            <p>Phone: (123) 456-7890</p>
          </address>
        </div>
      </div>
    </div>
  </footer>

app/views/items/index.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary" style="position:sticky;top:0px;z-index:5000;border-bottom: 5px solid green;">
    <div style="">
      <%= image_tag('logo-final.jpg', alt: 'Example Logo', style: 'height: 60px; width: 90px;') %>
    </div>

    <div class="container-fluid">
      <div class="navbar-brand" style="position:relative;bottom:1px"><%= link_to "HOME", root_path, style: "color: green;font-weight:700; font-size: 20px; padding-left: 15px;text-decoration: underline;position:relative;top:4px" %></div>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <div class="nav-link active" aria-current="page" style="position:relative; top:3px">
            <%= link_to "OFFERS", offers_path, style: "color: black;font-weight:700; font-size: 20px; padding-left: 15px; text-decoration: none;" %>
            </div>
          </li>
      <li>
      <% if @user %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="font-size: 20px;color: black;margin-left:15px;position:relative;top:3px">
              <b>PROFILE</b>
            </a>
            
              <ul class="dropdown-menu">
              
                <li><a class="dropdown-item" href="#">
                  <% if @user %>
                      <div style="display:flex;flex-direction:row;">
                        <p class="logged-text" style="margin-right:5px;">Login as: </p> <p class="email-log"><%= @user.email %></p>
                      </div>
                  <% else %>
                      <%= link_to "Login", login_path, style: "color: black; font-size: 20px; padding-left: 15px; text-decoration: none;" %>
                      <hr>
                      <%= link_to "Signup", signup_path, style: "color: black; font-size: 20px; padding-left: 15px; text-decoration: none;" %>
                      <hr>
                  <% end %> 
                </a></li>
                <% if @user %>
                  <li class="dropdown-item">
                  <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-primary", style:"background-color:red;margin-bottom:10px;position:absolute;bottom:53px" %>
                  <hr>
                  </li>
                <% end %>
                <li><%= link_to "VIEW PROFILE", profile_path, style: "text-decoration:none;", class:"profile-v" %></li>
              </ul>
              
          </li>
          <% end %>
    </li>
          
          <li class="nav-item" style="position:relative">
            <div class="nav-link active" aria-current="page" style="position:relative;top:3px">
            <%= link_to "CART🛒", carts_path, style: "color: black;font-weight:700; font-size: 20px; padding-left: 15px; text-decoration: none;" %>
            </div>
          </li>
          <% if @user==nil %>
            <li class="nav-item">
              <div class="nav-link active" aria-current="page">
              <%= link_to "Login", login_path, class: "btn btn-primary", style:"background-color:green;" %>
              </div>
              </li>
          <% end %>
          
        </ul>
        
        <div style="display:flex;flex-direction:column;position: absolute; top: 12px; left: 1035px; z-index: 1000;margin-top:10px">
          <%= form_tag('search', method: 'post') do %>
            <div class="d-flex flex-row justify-content-center align-items-center">
              <div class="mr-5" style="width:300px;margin-left:0px">
                <%= text_field_tag 'shop_name', nil, class: 'form-control', placeholder: '🔍 shop and items',oninput: "this.form.requestSubmit()", style:"border: 2px ridge green" %>
              </div>
              
            </div>
          <% end %>
          <div id="search_results" style="background-color:white"></div>
        </div>
        <div style="display:flex;flex-direction:row;position:absolute;left:550px;top:27px;">
          
          <%= link_to image_tag("location_logo.png", alt: "Image Description",style:"height: 30px;", id:"show-location-form")%>
          <%if session[:city] && session[:area]%>
            <div style="color: #3a3d3a; font-style: italic;font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;"><%= "#{session[:area]}, #{session[:city]}" %></div>
          <%end%>
          
        </div>


      </div>
    </div>
    
  </nav>




<div class="flex-container" style="margin-top: 100px">
  <% @items.each do |item| %>
    <div class="card" style="margin-right: 40px; margin-left: 75px; margin-bottom: 40px;border-radius: 10px;">
      <% if item.image.present? %>
          <%= image_tag(item.image, style: "width: 300px; height: 250px") %>
      <% end %>
      <h1 class="second-one-div"><%= item.item_name %></h1>
      <p class="second-one-div"><%=@rating_map[(item.id).to_s] %>⭐</p>
      <p class="first-one-div">₹<%= item.price %></p>
      <p class="price">Remaining: <%= item.quantity %></p>
      <%= form_tag({ controller: "items", action: "cart", method: "post" }) do %>
        <%= hidden_field_tag :item_id, item.id %>
        <%= label_tag :quantity, "Quantity:" %>
        <%= number_field_tag :quantity, 1, min: 1, max: item.quantity, style: "border-radius: 10px; border: 2px solid lightgreen;" %>
        <%= submit_tag "Add to Cart", class: "add-to-cart-button btn btn-primary", style: "margin-bottom:12px" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/items/payment.html.erb
<div style="display: flex;flex-direction:column;align-items: center;margin-bottom:50px;background-color: rgb(197, 154, 236);"><h1>PLACE YOUR ORDER🚚</h1></div>
<div style="margin-left: 2px;width: fit-content;font-family: Arial, sans-serif;font-size: 25px; color: #333; padding: 10px;background-color:rgb(133, 133, 225)">
  <% if @user %>
    <p class="second-one-div">Your address🏠: <%= @user.address %><p>
  <%end%>
</div>
<% order_details="" %>
<div style="display: flex;flex-direction: column;align-items: center;margin-top: 50px;padding:10px;border:solid black">
    <h2 style="color:green">ORDER SUMMARY</h2>
    <%if @items %>
        <% @items.each do |item| %>
            <div style="margin-bottom: 10px;"><h5><%= item.item_name %> x<%= @data[item.id.to_s]%>= ₹<%=(item.price.to_i)*(@data[item.id.to_s].to_i) %> </h5></div>
            <% order_details += "item_id: #{item.id}, item_name: #{item.item_name}, item_quantity: #{@data[item.id.to_s].to_i}, item_price: #{item.price.to_i} " %>
            <% order_details += "<br>"%>
        <%end%>
    <%end%>
    <h3>Total Amount:   ₹<%= @total_amount %> </h3>
    <% order_details+= "total_amount: #{@total_amount}" %>
    <% if @order %>
        <%= form_for(@order, url: orders_path, method: :post) do |f| %>
            <%= f.hidden_field :order_details, value: order_details %>
            <%= f.hidden_field :shop_id, value: @shop_id %>
            <%= f.hidden_field :seller_id, value: @seller_id %>
            <%= f.hidden_field :payment_check, value: true %>
            <%= f.hidden_field :amount, value: @total_amount %>

            <%= f.submit "Submit Order", class: "btn btn-primary", style: "background-color:green" %>
        <% end %>
    <% end %>

<div>